[build]
  publish = "public"
  functions = "api"

[[redirects]]
  from = "/"
  to = "/player.html"
  status = 200

[[redirects]]
  from = "/album/:albumId"
  to = "/.netlify/functions/makeSharePage?album=:albumId"
  status = 200

[[redirects]]
  from = "/album/:albumId/track/:trackId"
  to = "/.netlify/functions/makeSharePage?album=:albumId&track=:trackId"
  status = 200

[[redirects]]
  from = "/track/:trackId"
  to = "/.netlify/functions/makeSharePage?track=:trackId"
  status = 200

[[redirects]]
  from = "/track/:trackId/:slug"
  to = "/.netlify/functions/makeSharePage?track=:trackId"
  status = 200

[[headers]]
  for = "/player.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/site-settings.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
